### ISSUE TITLE
Document settings.json workspace key

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/help-pages#2]
To allow the user to change the Mu workspace.

**Comment by jonwitts** [comment]
This will also resolve issues #86, #178 and #87 if the documentation is updated about the workspace setting. A few examples would be useful too. I will work on a PR today if I get time.

**Comment by jonwitts** [comment]
PR submitted.

**Comment by carlosperate** [comment]
Closing as this page has been created: https://codewith.mu/en/tutorials/1.0/configuration
